export class details{
    public static teams = [
        'AL AHLY',
        'EL Gouna',
        'Zamalek',
        'Al Masry',
        'Pyramids',
        'Misr Lel Makkasa',
        'Al lttihad',
        'ENNPI',
        'Aswan',
        'Ismaily',
        'National Bank',
        'Smouha',
        'Wadi Degla',
        'Al Mokawloon',
        'El Gaish',
        'Ghazl El Mahalla',
        'Ceramica Cleopatra',
        'El Entag El Harby',
    ]
    // public static logos=[
    //     "../../assets/teams-logo/Al ITTIHAD.png",
    //     "../../assets/teams-logo/Al ITTIHAD.png",
    //     "../../assets/teams-logo/Al ITTIHAD.png",
    //     "../../assets/teams-logo/Al ITTIHAD.png",
    //     "../../assets/teams-logo/Al ITTIHAD.png",
    //     "../../assets/teams-logo/Al ITTIHAD.png",
    //     "../../assets/teams-logo/Al ITTIHAD.png",
    //     "../../assets/teams-logo/Al ITTIHAD.png",
    //     "../../assets/teams-logo/Al ITTIHAD.png",
    //     "../../assets/teams-logo/Al ITTIHAD.png",
    //     "../../assets/teams-logo/Al ITTIHAD.png",
    //     "../../assets/teams-logo/Al ITTIHAD.png",
    //     "../../assets/teams-logo/Al ITTIHAD.png",
    //     "../../assets/teams-logo/Al ITTIHAD.png",
    //     "../../assets/teams-logo/Al ITTIHAD.png",
    //     "../../assets/teams-logo/Al ITTIHAD.png",
    //     "../../assets/teams-logo/Al ITTIHAD.png",
    //     "../../assets/teams-logo/Al ITTIHAD.png",
    // ]
    public static referees=[
        'Mohammed Youssef',
        'Gehad Grisha',
        'Mahmoud Ashour',
        'Ahmed El Adawi',
        'Mohammed Sabahi',
        'Mohammed Adel',
        'Mohammed Hanafy',
        'Said Hamza',
        'Walid Abdelrazak',
        'Mahmoud Bassiouni',
        'Mahmoud El Banna',
        'Abdelaziz Sayed',
        'Tarek Magdi',
        'Mohamed Maarouf',
        'Ahmed Hamadi',
        'Mahmoud Nagy',
        'Ahmed Gamal',
        'Ibrahim Nour Eldin',
        'Amin Omar',
        'Ahmed El Ghandour',
        'Mohamed Salama'

    ]

}